dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.3.2
compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.3.2"

networks:
  default: bsc_test_moralis

dotenv: .env

wallets:
  from_key: ${PRIVATE_KEY}